---
resources:
 - name: repo
   type: git
   source:
    uri: {{app-url}}
    branch: master
    private_key: {{github-private-key}}
 - name: version
   type: git
   source:
    uri: {{app-url}}
    branch: version
    private_key: {{github-private-key}}
 - name: concourse
   type: git
   source:
    uri: {{concourse-scripts-url}}
    branch: master
 - name: tools
   type: git
   source:
    uri: {{pipeline-tools-url}}
    branch: master
 - name: m2
   type: docker-image
   source:
    repository: making/spring-pipeline-m2
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}
jobs:
  - name: generate-version
    public: true
    plan:
      - aggregate:
        - get: concourse
        - get: version
      - task: generate-version
        file: concourse/tasks/generate-version.yml
        params:
          - GIT_EMAIL: {{git-email}}
          - GIT_NAME: {{git-name}}
      - put: version
        params:
          repository: out

  - name: build-and-upload
    serial: true
    public: false
    plan:
      - aggregate:
        - get: tools
        - get: concourse
        - get: repo
        - get: m2
        - get: version
          resource: version
          passed: [ generate-version ]
          trigger: true
      - task: build-and-upload
        file: concourse/tasks/build-and-upload.yml
        params:
          - _JAVA_OPTIONS: -Djava.security.egd=file:/dev/./urandom
          - GIT_EMAIL: {{git-email}}
          - GIT_NAME: {{git-name}}
          - REDOWNLOAD_INFRA: {{redownload-infra}}
          - REDEPLOY_INFRA: {{redeploy-infra}}
          - EUREKA_GROUP_ID: {{eureka-group-id}}
          - EUREKA_ARTIFACT_ID: {{eureka-artifact-id}}
          - EUREKA_VERSION: {{eureka-version}}
          - STUBRUNNER_GROUP_ID: {{stubrunner-group-id}}
          - STUBRUNNER_ARTIFACT_ID: {{stubrunner-artifact-id}}
          - STUBRUNNER_VERSION: {{stubrunner-version}}
          - M2_SETTINGS_REPO_ID: {{m2-settings-repo-id}}
          - M2_SETTINGS_REPO_USERNAME: {{m2-settings-repo-username}}
          - M2_SETTINGS_REPO_PASSWORD: {{m2-settings-repo-password}}
          - REPO_WITH_JARS: {{repo-with-jars}}
          - M2_REPO: {{maven-local-dir}}
      - put: repo
        params:
          repository: out
          tag: out/target/tag
          only_tag: true

  - name: test-deploy
    serial: true
    public: false
    plan:
      - aggregate:
        - get: tools
        - get: concourse
        - get: repo
        - get: m2
        - get: version
          resource: version
          passed: [ build-and-upload ]
          trigger: true
      - task: test-deploy
        file: concourse/tasks/test-deploy.yml
        params:
          - _JAVA_OPTIONS: -Djava.security.egd=file:/dev/./urandom
          - GIT_EMAIL: {{git-email}}
          - GIT_NAME: {{git-name}}
          - REDOWNLOAD_INFRA: {{redownload-infra}}
          - REDEPLOY_INFRA: {{redeploy-infra}}
          - EUREKA_GROUP_ID: {{eureka-group-id}}
          - EUREKA_ARTIFACT_ID: {{eureka-artifact-id}}
          - EUREKA_VERSION: {{eureka-version}}
          - STUBRUNNER_GROUP_ID: {{stubrunner-group-id}}
          - STUBRUNNER_ARTIFACT_ID: {{stubrunner-artifact-id}}
          - STUBRUNNER_VERSION: {{stubrunner-version}}
          - REPO_WITH_JARS: {{repo-with-jars}}
          - M2_REPO: {{maven-local-dir}}
          - CF_TEST_USERNAME: {{cf-test-username}}
          - CF_TEST_PASSWORD: {{cf-test-password}}
          - CF_TEST_ORG: {{cf-test-org}}
          - CF_TEST_SPACE: {{cf-test-space}}
          - CF_API_URL: {{cf-api}}

  - name: test-smoke
    serial: true
    public: false
    plan:
      - aggregate:
        - get: tools
        - get: concourse
        - get: repo
        - get: m2
        - get: version
          resource: version
          passed: [ test-deploy ]
          trigger: true
      - task: test-smoke
        file: concourse/tasks/test-smoke.yml
        params:
          - _JAVA_OPTIONS: -Djava.security.egd=file:/dev/./urandom
          - GIT_EMAIL: {{git-email}}
          - GIT_NAME: {{git-name}}
          - REDOWNLOAD_INFRA: {{redownload-infra}}
          - REDEPLOY_INFRA: {{redeploy-infra}}
          - EUREKA_GROUP_ID: {{eureka-group-id}}
          - EUREKA_ARTIFACT_ID: {{eureka-artifact-id}}
          - EUREKA_VERSION: {{eureka-version}}
          - STUBRUNNER_GROUP_ID: {{stubrunner-group-id}}
          - STUBRUNNER_ARTIFACT_ID: {{stubrunner-artifact-id}}
          - STUBRUNNER_VERSION: {{stubrunner-version}}
          - REPO_WITH_JARS: {{repo-with-jars}}
          - M2_REPO: {{maven-local-dir}}
          - CF_TEST_USERNAME: {{cf-test-username}}
          - CF_TEST_PASSWORD: {{cf-test-password}}
          - CF_TEST_ORG: {{cf-test-org}}
          - CF_TEST_SPACE: {{cf-test-space}}
          - CF_API_URL: {{cf-api}}

  - name: test-rollback-deploy
    serial: true
    public: false
    plan:
      - aggregate:
        - get: tools
        - get: concourse
        - get: repo
        - get: m2
        - get: version
          resource: version
          passed: [ test-smoke ]
          trigger: true
      - task: test-rollback-deploy
        file: concourse/tasks/test-rollback-deploy.yml
        params:
          - _JAVA_OPTIONS: -Djava.security.egd=file:/dev/./urandom
          - GIT_EMAIL: {{git-email}}
          - GIT_NAME: {{git-name}}
          - REDOWNLOAD_INFRA: {{redownload-infra}}
          - REDEPLOY_INFRA: {{redeploy-infra}}
          - EUREKA_GROUP_ID: {{eureka-group-id}}
          - EUREKA_ARTIFACT_ID: {{eureka-artifact-id}}
          - EUREKA_VERSION: {{eureka-version}}
          - STUBRUNNER_GROUP_ID: {{stubrunner-group-id}}
          - STUBRUNNER_ARTIFACT_ID: {{stubrunner-artifact-id}}
          - STUBRUNNER_VERSION: {{stubrunner-version}}
          - REPO_WITH_JARS: {{repo-with-jars}}
          - M2_REPO: {{maven-local-dir}}
          - CF_TEST_USERNAME: {{cf-test-username}}
          - CF_TEST_PASSWORD: {{cf-test-password}}
          - CF_TEST_ORG: {{cf-test-org}}
          - CF_TEST_SPACE: {{cf-test-space}}
          - CF_API_URL: {{cf-api}}

  - name: test-rollback-smoke
    serial: true
    public: false
    plan:
      - aggregate:
        - get: tools
        - get: concourse
        - get: repo
        - get: m2
        - get: version
          resource: version
          passed: [ test-rollback-deploy ]
          trigger: true
      - task: test-rollback-smoke
        file: concourse/tasks/test-rollback-smoke.yml
        params:
          - _JAVA_OPTIONS: -Djava.security.egd=file:/dev/./urandom
          - GIT_EMAIL: {{git-email}}
          - GIT_NAME: {{git-name}}
          - REDOWNLOAD_INFRA: {{redownload-infra}}
          - REDEPLOY_INFRA: {{redeploy-infra}}
          - EUREKA_GROUP_ID: {{eureka-group-id}}
          - EUREKA_ARTIFACT_ID: {{eureka-artifact-id}}
          - EUREKA_VERSION: {{eureka-version}}
          - STUBRUNNER_GROUP_ID: {{stubrunner-group-id}}
          - STUBRUNNER_ARTIFACT_ID: {{stubrunner-artifact-id}}
          - STUBRUNNER_VERSION: {{stubrunner-version}}
          - REPO_WITH_JARS: {{repo-with-jars}}
          - M2_REPO: {{maven-local-dir}}
          - CF_TEST_USERNAME: {{cf-test-username}}
          - CF_TEST_PASSWORD: {{cf-test-password}}
          - CF_TEST_ORG: {{cf-test-org}}
          - CF_TEST_SPACE: {{cf-test-space}}
          - CF_API_URL: {{cf-api}}

  - name: stage-deploy
    serial: true
    public: false
    plan:
      - aggregate:
        - get: tools
        - get: concourse
        - get: repo
        - get: m2
        - get: version
          resource: version
          passed: [ test-rollback-smoke ]
          trigger: false
      - task: stage-deploy
        file: concourse/tasks/stage-deploy.yml
        params:
          - _JAVA_OPTIONS: -Djava.security.egd=file:/dev/./urandom
          - GIT_EMAIL: {{git-email}}
          - GIT_NAME: {{git-name}}
          - REDOWNLOAD_INFRA: {{redownload-infra}}
          - REDEPLOY_INFRA: {{redeploy-infra}}
          - EUREKA_GROUP_ID: {{eureka-group-id}}
          - EUREKA_ARTIFACT_ID: {{eureka-artifact-id}}
          - EUREKA_VERSION: {{eureka-version}}
          - STUBRUNNER_GROUP_ID: {{stubrunner-group-id}}
          - STUBRUNNER_ARTIFACT_ID: {{stubrunner-artifact-id}}
          - STUBRUNNER_VERSION: {{stubrunner-version}}
          - REPO_WITH_JARS: {{repo-with-jars}}
          - M2_REPO: {{maven-local-dir}}
          - CF_STAGE_USERNAME: {{cf-stage-username}}
          - CF_STAGE_PASSWORD: {{cf-stage-password}}
          - CF_STAGE_ORG: {{cf-stage-org}}
          - CF_STAGE_SPACE: {{cf-stage-space}}
          - CF_API_URL: {{cf-api}}

  - name: stage-e2e
    serial: true
    public: false
    plan:
      - aggregate:
        - get: tools
        - get: concourse
        - get: repo
        - get: m2
        - get: version
          resource: version
          passed: [ stage-deploy ]
          trigger: false
      - task: stage-smoke
        file: concourse/tasks/stage-e2e.yml
        params:
          - _JAVA_OPTIONS: -Djava.security.egd=file:/dev/./urandom
          - GIT_EMAIL: {{git-email}}
          - GIT_NAME: {{git-name}}
          - REDOWNLOAD_INFRA: {{redownload-infra}}
          - REDEPLOY_INFRA: {{redeploy-infra}}
          - EUREKA_GROUP_ID: {{eureka-group-id}}
          - EUREKA_ARTIFACT_ID: {{eureka-artifact-id}}
          - EUREKA_VERSION: {{eureka-version}}
          - STUBRUNNER_GROUP_ID: {{stubrunner-group-id}}
          - STUBRUNNER_ARTIFACT_ID: {{stubrunner-artifact-id}}
          - STUBRUNNER_VERSION: {{stubrunner-version}}
          - REPO_WITH_JARS: {{repo-with-jars}}
          - M2_REPO: {{maven-local-dir}}
          - CF_STAGE_USERNAME: {{cf-stage-username}}
          - CF_STAGE_PASSWORD: {{cf-stage-password}}
          - CF_STAGE_ORG: {{cf-stage-org}}
          - CF_STAGE_SPACE: {{cf-stage-space}}
          - CF_API_URL: {{cf-api}}

  - name: prod-deploy
    serial: true
    public: false
    plan:
      - aggregate:
        - get: tools
        - get: concourse
        - get: repo
        - get: m2
        - get: version
          resource: version
          passed: [ stage-e2e ]
          trigger: false
      - task: prod-deploy
        file: concourse/tasks/prod-deploy.yml
        params:
          - _JAVA_OPTIONS: -Djava.security.egd=file:/dev/./urandom
          - GIT_EMAIL: {{git-email}}
          - GIT_NAME: {{git-name}}
          - REDOWNLOAD_INFRA: {{redownload-infra}}
          - REDEPLOY_INFRA: {{redeploy-infra}}
          - EUREKA_GROUP_ID: {{eureka-group-id}}
          - EUREKA_ARTIFACT_ID: {{eureka-artifact-id}}
          - EUREKA_VERSION: {{eureka-version}}
          - STUBRUNNER_GROUP_ID: {{stubrunner-group-id}}
          - STUBRUNNER_ARTIFACT_ID: {{stubrunner-artifact-id}}
          - STUBRUNNER_VERSION: {{stubrunner-version}}
          - REPO_WITH_JARS: {{repo-with-jars}}
          - M2_REPO: {{maven-local-dir}}
          - CF_PROD_USERNAME: {{cf-prod-username}}
          - CF_PROD_PASSWORD: {{cf-prod-password}}
          - CF_PROD_ORG: {{cf-prod-org}}
          - CF_PROD_SPACE: {{cf-prod-space}}
          - CF_API_URL: {{cf-api}}
      - put: repo
        params:
          repository: out
          tag: out/target/tag
          only_tag: true

  - name: prod-complete
    serial: true
    public: false
    plan:
      - aggregate:
        - get: tools
        - get: concourse
        - get: repo
        - get: m2
        - get: version
          resource: version
          passed: [ prod-deploy ]
          trigger: true
      - task: prod-complete
        file: concourse/tasks/prod-complete.yml
        params:
          - _JAVA_OPTIONS: -Djava.security.egd=file:/dev/./urandom
          - GIT_EMAIL: {{git-email}}
          - GIT_NAME: {{git-name}}
          - REDOWNLOAD_INFRA: {{redownload-infra}}
          - REDEPLOY_INFRA: {{redeploy-infra}}
          - EUREKA_GROUP_ID: {{eureka-group-id}}
          - EUREKA_ARTIFACT_ID: {{eureka-artifact-id}}
          - EUREKA_VERSION: {{eureka-version}}
          - STUBRUNNER_GROUP_ID: {{stubrunner-group-id}}
          - STUBRUNNER_ARTIFACT_ID: {{stubrunner-artifact-id}}
          - STUBRUNNER_VERSION: {{stubrunner-version}}
          - REPO_WITH_JARS: {{repo-with-jars}}
          - M2_REPO: {{maven-local-dir}}
          - CF_PROD_USERNAME: {{cf-prod-username}}
          - CF_PROD_PASSWORD: {{cf-prod-password}}
          - CF_PROD_ORG: {{cf-prod-org}}
          - CF_PROD_SPACE: {{cf-prod-space}}
          - CF_API_URL: {{cf-api}}

  - name: init-m2
    plan:
      - aggregate:
        - get: repo
        - get: concourse
      - task: build-m2
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: making/alpine-java-bash-git
          inputs:
            - name: repo
            - name: concourse
          outputs:
            - name: to-push
          run:
            path: sh
            args:
            - concourse/tasks/cache-m2.sh
            - init
      - put: m2
        params:
          import_file: to-push/rootfs.tar

  - name: update-m2
    plan:
      - aggregate:
        - get: repo
          trigger: true
        - get: concourse
        - get: m2
      - task: build-m2
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: making/alpine-java-bash-git
          inputs:
            - name: repo
            - name: concourse
            - name: m2
          outputs:
            - name: to-push
          run:
            path: sh
            args:
            - concourse/tasks/cache-m2.sh
      - put: m2
        params:
          import_file: to-push/rootfs.tar
