---
resources:
 - name: repo
   type: git
   source:
    uri: {{app-url}}
    branch: master
    private_key: {{github-private-key}}
 - name: version
   type: git
   source:
    uri: {{app-url}}
    branch: version
    private_key: {{github-private-key}}
 - name: tools
   type: git
   source:
    uri: {{tools-url}}
    branch: master
   submodules: all

jobs:
  - name: generate-version
    public: true
    plan:
      - aggregate:
        - get: tools
        - get: version
      - task: generate-version
        file: tools/tasks/generate-version.yml
        params:
          - GIT_EMAIL: {{git-email}}
          - GIT_NAME: {{git-name}}
      - put: version
        params:
          repository: out

  - name: build-and-upload
    serial: true
    public: false
    plan:
      - aggregate:
        - get: tools
        - get: repo
        - get: version
          resource: version
          passed: [ generate-version ]
          trigger: true
      - task: build-and-upload
        file: tools/tasks/build-and-upload.yml
        params:
          - _JAVA_OPTIONS: -Djava.security.egd=file:/dev/./urandom
          - GIT_EMAIL: {{git-email}}
          - GIT_NAME: {{git-name}}
          - REDOWNLOAD_INFRA: {{redownload-infra}}
          - REDEPLOY_INFRA: {{redeploy-infra}}
          - EUREKA_GROUP_ID: {{eureka-group-id}}
          - EUREKA_ARTIFACT_ID: {{eureka-artifact-id}}
          - EUREKA_VERSION: {{eureka-version}}
          - STUBRUNNER_GROUP_ID: {{stubrunner-group-id}}
          - STUBRUNNER_ARTIFACT_ID: {{stubrunner-artifact-id}}
          - STUBRUNNER_VERSION: {{stubrunner-version}}
          - M2_SETTINGS_REPO_ID: {{m2-settings-repo-id}}
          - M2_SETTINGS_USERNAME: {{m2-settings-username}}
          - M2_SETTINGS_PASSWORD: {{m2-settings-password}}
          - REPO_WITH_JARS: {{repo-with-jars}}
      - put: repo
        params:
          repository: repo
          tag: repo/target/tag
          only_tag: true

  - name: test-deploy
    serial: true
    public: false
    plan:
      - aggregate:
        - get: tools
        - get: repo
        - get: version
          resource: version
          passed: [ build-and-upload ]
          trigger: true
      - task: test-deploy
        file: tools/tasks/test-deploy.yml
        params:
          - _JAVA_OPTIONS: -Djava.security.egd=file:/dev/./urandom
          - GIT_EMAIL: {{git-email}}
          - GIT_NAME: {{git-name}}
          - REDOWNLOAD_INFRA: {{redownload-infra}}
          - REDEPLOY_INFRA: {{redeploy-infra}}
          - EUREKA_GROUP_ID: {{eureka-group-id}}
          - EUREKA_ARTIFACT_ID: {{eureka-artifact-id}}
          - EUREKA_VERSION: {{eureka-version}}
          - STUBRUNNER_GROUP_ID: {{stubrunner-group-id}}
          - STUBRUNNER_ARTIFACT_ID: {{stubrunner-artifact-id}}
          - STUBRUNNER_VERSION: {{stubrunner-version}}
          - M2_SETTINGS_REPO_ID: {{m2-settings-repo-id}}
          - M2_SETTINGS_USERNAME: {{m2-settings-username}}
          - M2_SETTINGS_PASSWORD: {{m2-settings-password}}
          - REPO_WITH_JARS: {{repo-with-jars}}

#- name: job-show-date
#  plan:
#  - get: resource-tutorial
#  - get: resource-gist
#    passed: [job-bump-date]
#    trigger: true
#  - task: show-date
#    config:
#      platform: linux
#      image_resource:
#        type: docker-image
#        source: {repository: busybox}
#      inputs:
#        - name: resource-gist
#      run:
#        path: cat
#        args: [resource-gist/bumpme]
