---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: frolvlad/alpine-oraclejdk8
inputs:
  - name: tools
  - name: concourse
  - name: repo
  - name: version
outputs:
  - name: output
run:
  path: /bin/bash
  args:
    - concourse/tasks/build-and-upload.sh
