---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk-alpine
inputs:
  - name: tools
  - name: concourse
  - name: repo
  - name: version
outputs:
  - name: output
run:
  path: /bin/sh
  args:
    - concourse/tasks/build-and-upload.sh
