---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk
inputs:
  - name: version
  - name: tools
outputs:
  - name: out
run:
  path: /bin/bash
  args:
    - tools/tasks/generate-version.sh
