---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk
inputs:
  - name: version
  - name: concourse
outputs:
  - name: out
run:
  path: /bin/sh
  args:
    - concourse/tasks/generate-version.sh
