---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: making/alpine-java-bash-git
inputs:
  - name: version
  - name: concourse
outputs:
  - name: out
run:
  path: /bin/bash
  args:
    - concourse/tasks/generate-version.sh
